steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
        ['build', '-t', 'gcr.io/rebatemango-dev/k8-deployment', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rebatemango-dev/k8-deployment']
  - name: 'mount'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
        args: ['public', '/persistent_volume/file']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
        - 'set'
        - 'image'
        - 'deployments/myapp'
        - 'web=gcr.io/rebatemango-dev/k8-deployment'
    env:
        - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b'
        - 'CLOUDSDK_CONTAINER_CLUSTER=rebate-cluster-dev'